"""add practice_assignment and notification

Revision ID: 1001736c2ef5
Revises: 2233fb875617
Create Date: 2026-08-16 08:18:00.556399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1001736c2ef5'
down_revision = '2233fb875617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_assignment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_column('practice_assignment')

    # ### end Alembic commands ###
