"""add department and report tables

Revision ID: 2233fb875617
Revises: 4bc4e72a33c6
Create Date: 2026-08-14 14:29:37.439625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2233fb875617'
down_revision = '4bc4e72a33c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('affected_record_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('affected_table', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('old_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=60), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('new_value')
        batch_op.drop_column('old_value')
        batch_op.drop_column('affected_table')
        batch_op.drop_column('affected_record_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
