"""add department and report tables

Revision ID: 2233fb875617
Revises: 4bc4e72a33c6
Create Date: 2026-08-14 14:29:37.439625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2233fb875617'
down_revision = '4bc4e72a33c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('affected_record_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('affected_table', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('old_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=60), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))

    op.create_table('employee_daily_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('today_work', sa.Text(), nullable=False),
        sa.Column('what_learned', sa.Text(), nullable=False),
        sa.Column('daily_status', sa.String(length=20), nullable=False),
        sa.Column('overall_progress', sa.Integer(), nullable=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('is_frozen', sa.Boolean(), nullable=False),
        sa.Column('frozen_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date', name='uq_emp_report_user_date')
    )

    op.create_table('intern_daily_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('training_details', sa.Text(), nullable=True),
        sa.Column('training_status', sa.String(length=30), nullable=True),
        sa.Column('training_progress', sa.Integer(), nullable=True),
        sa.Column('meeting_details', sa.Text(), nullable=True),
        sa.Column('meeting_status', sa.String(length=30), nullable=True),
        sa.Column('meeting_notes', sa.Text(), nullable=True),
        sa.Column('practice_details', sa.Text(), nullable=True),
        sa.Column('practice_status', sa.String(length=30), nullable=True),
        sa.Column('practice_progress', sa.Integer(), nullable=True),
        sa.Column('overall_status', sa.String(length=30), nullable=True),
        sa.Column('is_frozen', sa.Boolean(), nullable=False),
        sa.Column('frozen_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'date', name='uq_intern_report_user_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intern_daily_reports')
    op.drop_table('employee_daily_reports')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('new_value')
        batch_op.drop_column('old_value')
        batch_op.drop_column('affected_table')
        batch_op.drop_column('affected_record_id')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
